# Generated by Django 3.2.7 on 2021-09-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Processing'), (3, 'Completed')], default=1)),
                ('meeting_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('video', models.FilePathField(blank=True)),
                ('task_id', models.CharField(blank=True, max_length=64)),
            ],
        ),
    ]
