# Generated by Django 3.2.7 on 2021-10-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_alter_record_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Processing'), (3, 'Completed'), (4, 'Error'), (5, 'Notfound')], default=1),
        ),
    ]
